### ISSUE TITLE
Maintain hashes

### ISSUE THREAD

**Issue by jme783** [aymericbeaumet/metalsmith-redirect#12]
I notice that redirects now strip off any URL hashes (i.e. `https://foo.com#bar`) when redirecting. Is there a setting to enable this, or can this be something added to the library?

Many thanks,

Jeff

**Comment by aymericbeaumet** [comment]
Is that happening in the source or the destination url?

**Comment by jme783** [comment]
When the _source_ URL has a hash in it, it is stripped after the redirect in the _destination_ URL

**Comment by aymericbeaumet** [comment]
When redirecting from `source` to `destination`, you expect `source#hash` to point to `destination#hash`?

**Comment by jme783** [comment]
@aymericbeaumet yes correct, that would be my expectation

**Comment by aymericbeaumet** [comment]
This feature has been implemented with the latest release, thanks for your patience 👴
