### ISSUE TITLE
set redirection in markdown frontmatter

### ISSUE THREAD

**Issue by oupala** [aymericbeaumet/metalsmith-redirect#13]
It could be great if the redirection could be set in markdown frontmatter instead of metalsmith js file.

This could permit to embed the origin redirected url along with the real document and its url.

**Comment by aymericbeaumet** [comment]
This could happen as long as metalsmith-redirect is be called before any markdown compiler plugin, otherwise the frontmatter information is lost.

Maybe something along those lines to create a redirection from `/about` to `/about-me`:

```yaml
# /about.md
---
redirect: /about-me
---
```

wdyt?

**Comment by aymericbeaumet** [comment]
Options I consider adding:
- boolean to enable redirections extraction from markdown frontmatter (default: false)
- string to customize the frontmatter key (default: `redirect`)
  * allow deep path: `a.b.c.redirect`?
- boolean to keep the markdown files from which a redirection has been extracted from (default: false)

**Comment by aymericbeaumet** [comment]
This is now working with the latest version via [`options.frontmatter`](https://github.com/aymericbeaumet/metalsmith-redirect#optionsfrontmatter) 👍

**Comment by oupala** [comment]
I tried this new version 3.0.1 of the plugin, but I can't make it work well.

I have a a file where I added the following key to the frontmatter of `new.md`:

```yaml
redirectFrom: /old
```

And the redirection file created is redirecting the wrong url:

```html
<meta http-equiv=refresh content="0;url=/old/new/index.html">
```

I'm also using metalsmith-permalink and I'm calling it before metalsmith-redirect.

Any clue?

**Comment by oupala** [comment]
And by the way I never manager to make the previous version of the plugin (version 2.x.x) to work as mentioned in your [first comment](#issuecomment-522825036) of this thread.

**Comment by aymericbeaumet** [comment]
This specific issue is not coming from metalsmith-permalink, even though it is better to place metalsmith-redirect after all the plugins which change the urls/filenames (otherwise you might create redirections to non-existing files, e.g. .md files which are going to be compiled into .html files). I'm going to add a note about this in the readme.

The problem you are facing is caused by the absence of leading slash in the way metalsmith deals with its virtual filesystem. This causes the filepaths to be considered relative to the source, hence `/old/new/index.html` instead `/new/index.html`.

> And by the way I never manager to make the previous version of the plugin (version 2.x.x) to work as mentioned in your first comment of this thread.

The previous version didn't support gathering redirections from the frontmatters. I was thinking outloud about the design of the feature, sorry for misleading you :)

**Comment by aymericbeaumet** [comment]
@oupala I just published the fix 👉 `metalsmith-redirect@3.0.2`

**Comment by oupala** [comment]
Waiting for npmjs release to test it.

**Comment by aymericbeaumet** [comment]
It's already published 👍

**Comment by oupala** [comment]
It works like a charm, thanks!

**Comment by oupala** [comment]
It seems that the *redirection* feature is not compatible with the [metalsmith-broken-link-checker](https://github.com/davidxmoody/metalsmith-broken-link-checker).

When I use `redirectFrom` directive in a yaml frontmatter of a markdown file, the redirectedFrom url is not added to the list of urls managed by metalsmith. Hence, metalsmith-broken-link-checker detect that a link to an old url (redirected to a new one) is broken, while it is in reality not really broken as a redirection exists.

What do you think of this problem?

**Comment by aymericbeaumet** [comment]
See https://github.com/aymericbeaumet/metalsmith-redirect/issues/19
