### ISSUE TITLE
Incompatibility with metalsmith-broken-link-checker

### ISSUE THREAD

**Issue by aymericbeaumet** [aymericbeaumet/metalsmith-redirect#19]
_From https://github.com/aymericbeaumet/metalsmith-redirect/issues/13#issuecomment-529449106 by @oupala:_

> It seems that the *redirection* feature is not compatible with the [metalsmith-broken-link-checker](https://github.com/davidxmoody/metalsmith-broken-link-checker).

> When I use `redirectFrom` directive in a yaml frontmatter of a markdown file, the redirectedFrom url is not added to the list of urls managed by metalsmith. Hence, metalsmith-broken-link-checker detect that a link to an old url (redirected to a new one) is broken, while it is in reality not really broken as a redirection exists.

> What do you think of this problem?

**Comment by aymericbeaumet** [comment]
I think what matters here is the order in which you register the plugins. I have been able to properly use _metalsmith-redirect_ along with _metalsmith-broken-link-checker_ if the former is loaded first. 

When loaded first, it has a chance to create all the redirections before metalsmith-broken-link-checker runs.

`redirectFrom` and `redirectTo` are technically only mutating the `files` object Metalsmith passes through all the plugins, the same object _metalsmith-broken-link-checker_ uses to perform its static checks. I'm not sure about the concept of urls managed by metalsmith.

I have updated the FAQ + added functional tests in https://github.com/aymericbeaumet/metalsmith-redirect/pull/20.

**Comment by oupala** [comment]
I **am** loading **and** calling `metalsmith-redirect` before `metalsmith-broken-link-checker`.

I saw that you added some functional test to check if both plugins are compatible.

I don't understand why it doesn't work for me!

> Error: You have 1 broken links:
> 
> tutorial/index.html >>> href: "/tutorial-old-url", text: "old url"

And my js script:

```js
[...]
var Handlebars         = require('handlebars'),
    Metalsmith         = require('metalsmith'),
[...]
    permalinks         = require('metalsmith-permalinks'),
    redirect           = require('metalsmith-redirect'),
    brokenLinkChecker  = require('metalsmith-broken-link-checker'),
[...]
var metalsmith = new Metalsmith(__dirname);
[...]
metalsmith
[...]
  .use(redirect({
    frontmatter: true,
    preserveHash: true
  }));

if (mode === 'dev') {
[...]
} else {
  metalsmith
    .use(brokenLinkChecker({
      warn: false
    }))
    .use(htmlMinifier())
    .use(gzip());
}

metalsmith.build(function (err) {
  'use strict';
  if (err) {
    throw err;
  }
});
```

**Comment by aymericbeaumet** [comment]
Hum interesting, can you provide a git repository reproducing the issue? This will help me dig the problem.

**Comment by aymericbeaumet** [comment]
@oupala I'm going to close this for now. Feel free to reopen the issue when you provide more details so I can dig into it.

**Comment by oupala** [comment]
I can't reopen the issue by myself.

I now have a minimal test case to reproduce the issue. What is your preferred way so that I can send it to you?

**Comment by aymericbeaumet** [comment]
A public git repository would be the easiest if it's possible for you.

**Comment by oupala** [comment]
[Here it is!](https://frama.link/test-metalsmith)

**Comment by aymericbeaumet** [comment]
Thank you, can you confirm the command I should execute to see the actual error? Running `npm install && npm start` produces a _build_ folder as expected.

**Comment by oupala** [comment]
The command you should execute is `npm start` as you stated. There is no error, just a warning because I set `warn: true` to *broken link checker* configuration:

https://github.com/oupala/test-metalsmith/blob/b674d04284fca956fdd3b3a8c09db58d41a484cf/index.js#L35

But you should see the warning when executing.

```bash
$ npm start

> debug-example@1.0.0 start /path/to/test-metalsmith
> node index.js

test/index.html >>> href: "test-old-url", text: "old url"
```

You can also set `warn: false` if you want to get an error.

```
$ npm start

> debug-example@1.0.0 start /path/to/test-metalsmith
> node index.js

/path/to/test-metalsmith/index.js:41
    throw err;
    ^

Error: You have 1 broken links:

test/index.html >>> href: "test-old-url", text: "old url"
    at maybeThrow (/path/to/test-metalsmith/node_modules/metalsmith-broken-link-checker/src/handle-links.js:17:11)
    at /path/to/test-metalsmith/node_modules/metalsmith-broken-link-checker/src/handle-links.js:26:7
    at /path/to/test-metalsmith/node_modules/ramda/src/internal/_pipe.js:3:14
    at /path/to/test-metalsmith/node_modules/ramda/src/internal/_arity.js:10:19
    at Ware.<anonymous> (/path/to/test-metalsmith/node_modules/metalsmith-broken-link-checker/src/index.js:81:6)
    at Ware.<anonymous> (/path/to/test-metalsmith/node_modules/wrap-fn/index.js:75:16)
    at Ware.<anonymous> (/path/to/test-metalsmith/node_modules/wrap-fn/index.js:57:27)
    at next (/path/to/test-metalsmith/node_modules/ware/lib/index.js:85:20)
    at /path/to/test-metalsmith/node_modules/wrap-fn/index.js:121:18
    at Ware.<anonymous> (/path/to/test-metalsmith/node_modules/metalsmith-redirect/index.js:72:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! debug-example@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the debug-example@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!    /path/to/.npm/_logs/2019-09-28T09_26_11_415Z-debug.log
```

**Comment by aymericbeaumet** [comment]
Interestingly enough, there was a problem in the way the relative links were computed. Thanks to you I was able to find it, and it was fixed in https://github.com/aymericbeaumet/metalsmith-redirect/pull/21 (now released as `metalsmith-redirect@3.0.3`).

The thing is, even with this fix, your repo would not build. Why? Because in your example your link points to `test-old-url`, but the file actually generated by this plugin is `test-old-url/index.html`. You can confirm this by adding `.use(files => console.log(files))` just before/after you use this plugin to see what has happened.

So in the end, it looks like there is a bug in `metalsmith-broken-link-checker` as we would expect it to apply a fallback strategy where it would try appending `/index.html` to every link which looks like a directory (`path.extname(link) === ''` in a web environment).

If you want to confirm this, in your case it works if you change `[old url](test-old-url)` for `[old url](test-old-url/index.html)`.

**Comment by aymericbeaumet** [comment]
From the readme it seems metalsmith-broken-link-checker is supposed to support this, you should definitely open an issue there.

**Comment by oupala** [comment]
I do confirm that metalsmith-redirect@3.0.3 works as expected and that the workaround you mention make the build ends succesfully.

I have opened an issue in th metalsmith-broken-link-checker repository.
