### ISSUE TITLE
Write a .htaccess file

### ISSUE THREAD

**Issue by RobLoach** [aymericbeaumet/metalsmith-redirect#5]
Create an .htaccess with redirects for Apache.

**Comment by aymericbeaumet** [comment]
How would you do that? Side by side with the actual redirections? I don't want to clutter this plugin.

**Comment by RobLoach** [comment]
Agreed, keeping simplicity is key... Perhaps queue up all the redirects, and then write `/.htaccess` before calling `return done()`?

**Comment by aymericbeaumet** [comment]
Hum I guess it should be exclusive, you don't need to bother with client-side redirections if you can do URL rewrite server-side.

**Comment by aymericbeaumet** [comment]
Closing this issue for now, feel free to re-open if you think this should be part of this plugin.
